# Generated by Django 3.2.9 on 2022-07-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20220727_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight_book',
            name='flight',
        ),
    ]
